name: 'Create site with all documentation versions'

inputs:

  token:
    description: 'GitHub Token'
    required: true

  repository:
    description: 'GitHub Repository'
    required: true
  
  disable_branch_docs:
    description: 'Disable branch documentation'
    required: false
    default: 'false'

runs:
  using: 'docker'  
  image: docker://ghcr.io/syna-astra-dev/action-doc-publish/create-site:v4
  env:
    GITHUB_TOKEN: ${{ inputs.token }}
    GITHUB_REPOSITORY: ${{ inputs.repository }}
    WEBSITE_ADDRESS: ${{ inputs.website_address }}
    DISABLE_BRANCH_DOCS: ${{ inputs.disable_branch_docs }}
